id: P341CA240
initial_creation_type: input
source_metadata:
  title: Khenpo Gangshar Wangpo
  language: bo
  description: 'Texts by the Dzogchen teacher Khenpo Gangshar Wangpo (mkhan po gang
    shar dbang po, 1925–1958/9), who is known especially for his role as the root
    teacher of Chögyam Trungpa:'
  volume:
    57a62a6040794fdc841c360054fd5f7c:
      title: A Way of Settling into the Realization of Mind’s Essence
      parent: Advice
    1283e4fdb8a14bbd89ec8732624a9e65:
      title: A Song of Advice for Gok Zangden
      parent: Dzogchen
    a60c6c5f55af4b07a15b2a39d9173ae4:
      title: A Song to Introduce the Unmistaken View of the Great Perfection
      parent: Dzogchen
    990dfa369dca4e9dabc83c29131d6c54:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Dzogchen
    44cdbb0dbed640d781064e26b2815a31:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Dzogchen
    abdb5d0fc5724cfa88d67960cbc9f6e6:
      title: 'Vomiting Gold: A Pith Instruction in the Form of Advice for the Diligent
        Practitioner, the Excellent Atsang'
      parent: Dzogchen
    23d9acef652d4b96ba152f7d5d12a5c0:
      title: 'Guru Yoga: The Consummate Blessing'
      parent: Guru Yoga
    d5638d79f4b24cd0bef2300a6e399f11:
      title: 'From the Mahāmudrā Preliminary Practices: Continuous Integration with
        Ground, Path, and Fruition'
      parent: Mahāmudrā
    bf27c6eb9ee64f0ca6fec581dff0ea44:
      title: Prayer to Pacify Military Conflict
      parent: Prayers
created_at: '2022-03-01T00:25:04.702418'
last_modified_at: '2022-03-01T00:25:04.702421'
statistics:
  total_words: 2959
  total_non_words: 329
quality:
  non_words_ratio: 0.11
